version: '2.4'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"

  receiver-service:
    build: ./receiver-service
    ports:
      - "${RECEIVER_PORT}:3000"
    environment:
      MONGODB_URI: "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@${MONGO_HOST}:27017/${MONGO_RECEIVER_DB}?authSource=admin"
      REDIS_HOST: ${REDIS_HOST}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb
      - redis

  listener-service:
    build: ./listener-service
    environment:
      MONGODB_URI: "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@${MONGO_HOST}:27017/${MONGO_LISTENER_DB}?authSource=admin"
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb_data: